### ISSUE TITLE
working with Style transfer 

### ISSUE THREAD

**Issue by arrrrr3186** [rootSue/Causal-RSGAN#1]
Hello, 

I am working on Style transfer, from SAR to Optical images. 

for that I want to try out your repo.

but before that I have few questions, It will be great if you can answer them for me.
1. which python version should be used,
2. As I check "[stylegan2-ada-pytorch](https://github.com/NVlabs/stylegan2-ada-pytorch)", they have mention we need pass a ZIP or folder path of images, is this folder should contains the 2 types of images (for my case SAR and Optical ) or something else.

**Comment by rootSue** [comment]
Thank you for your interest in our work. 
1. For your first question, we are using python version 3.7, for our environment you can refer to this link https://github.com/NVlabs/stylegan2-ada-pytorch. 
2. For the second question, unfortunately our code is not directly applicable to the style transfer task, the structure of the network would not be suitable. It is only suitable for processing one type of image. But I'm sure there are models on github for style transfer based on stylegan2, it may take you some more time to find them.----- 原始邮件 -----
发件人：arrrrr3186 ***@***.***>
收件人：rootSue/Causal-RSGAN ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[rootSue/Causal-RSGAN] working with Style transfer  (Issue #1)
日期：2024年06月11日 18点14分


Hello,
I am working on Style transfer, from SAR to Optical images.
for that I want to try out your repo.
but before that I have few questions, It will be great if you can answer them for me.

which python version should be used,
As I check "stylegan2-ada-pytorch", they have mention we need pass a ZIP or folder path of images, is this folder should contains the 2 types of images (for my case SAR and Optical ) or something else.

**Comment by arrrrr3186** [comment]
Thank you for reply and clarification.
